<h1>Terms of Use</h1>


<p />PLEASE READ THESE TERMS OF USE CAREFULLY BECAUSE THEY DESCRIBE YOUR RIGHTS AND RESPONSIBILITIES

<p />This is the official Terms of Use Agreement ("Agreement") for http://www.ratemycampus.com/ ("Site," "we," "us," or "our"), an Internet website. This Agreement governs only the content, features, and activities related to this Site and does not cover websites for any holding company, Parent Companies and any subsidiaries and affiliates of RMC and the Parent Companies (collectively, "Affiliates"), or for any other company, unless specifically stated.

<p />This Site is offered and made available only to users 16 years of age or older who reside in the United States of America, its territories and possessions ("U.S.") and certain features on this Site (including, but not limited to, user registration) may be subject to heightened age and/or other eligibility requirements. If you are not yet 16 years old or the required greater age for certain features, do not reside in the U.S. and/or do not meet any other eligibility requirements, please discontinue using the Site immediately or, if for any reason, you do not agree with all of the terms and conditions contained in this Agreement, please discontinue using the Site immediately, because by using or attempting to use the Site, you certify that you are at least 18 years of age or other required greater age for certain features and meet any other eligibility and residency requirements of the Site.

<p />These terms and conditions regarding your use of the Site constitute a legally binding agreement between you and the Site and the Parent Companies. In this Agreement, the term "Site" includes all websites and web pages within the Site as well as any equivalent, mirror, replacement, substitute or backup websites and web pages that are associated with the Site. By using this Site, you understand, acknowledge and agree that you will abide by the terms of this Agreement and any additional terms that govern certain products and services, which will be presented in conjunction with those products and services ("Additional Terms"). The Site may also provide rules of participation ("Rules") for certain activities and services including, but not limited to, contests and sweepstakes, award programs, membership clubs, and email. The Site's Additional Terms, Privacy Policy and the Rules are hereby incorporated in this Agreement by reference. To the extent that there is a conflict between this Agreement and Additional Terms for the activity in which you choose to participate, the Additional Terms shall govern. To the extent that there is a conflict between this Agreement and the specific Rules for the activity in which you choose to participate, the Rules shall govern. This Agreement will remain in full force and effect as long as you are a user of the Site and in the event of termination of any membership, service or feature, you will still be bound by your obligations under this Agreement, the Privacy Policy and any Additional Terms or Rules, including any indemnifications, warranties and limitations of liability.

<p />The words "use" or "using" in this Agreement, means any time an individual (a "user"), directly or indirectly, with or without the aid of a machine or device, does or attempts to access, interact with use, display, view, print or copy from the Site, transmit, receive or exchange data or communicate with the Site, or in any way utilizes, benefits, takes advantage of or interacts with any function, service or feature of the Site, for any purpose whatsoever. This Agreement does not cover your rights or responsibilities with respect to third party content or sites or any links that may direct your browser or your connection to third party sites or pages. This is the entire and exclusive Agreement between you and us regarding use of the Site and it cannot be modified, except as specifically described below in Section 2.

<p /><strong>1. REGISTRATION</strong>
<br />We may require each user to have a unique user name, email address, and password combination in order to access and use certain features or functions of the Site and may also, from time to time, provide users with additional codes or passwords necessary to access and use certain features or functions of the Site. Please read our Privacy Policy, which describes the personally identifiable information ("Personal Information") we collect, use, disclose, manage and store. As part of the registration process for the feature or function, you will choose a user name and password (or we may assign an initial password which we will give you the option to change). Your user name and password are personal to you and you may not allow any others to use your user name or password under any circumstances. We are not liable for any harm caused or related to the theft or misappropriation of your user name or password, disclosure of your user name or password, or your authorization of anyone else to use your user name or password. You agree to immediately notify us if you become aware of or believe there is or may have been any unauthorized use of (or activity using) your user name or password or any other need to deactivate your user name or password due to security concerns.

<p /><strong>2. MODIFICATIONS</strong>
<br />We reserve the right, at any time and from time to time, for any reason in our sole discretion, to change the terms of this Agreement. We will post or display notices of material changes on the Site and/or e-mail you or notify you upon login about these changes; the form of such notice is at our discretion. Once we post them on the Site, these changes become effective immediately and if you use the Site after they become effective it will signify your agreement to be bound by the changes. You should check back frequently and review the terms and conditions of this Agreement, including, but not limited to, other Additional Terms, Rules and Privacy Policy, regularly so you are aware of the most current rights and obligations that apply to you and the terms and conditions of your agreement with us. 

<p /><strong>3. OWNERSHIP OF INTELLECTUAL PROPERTY</strong>
<br />The contents of this Site, including all Site software, design, text, images, photographs, illustrations, audio and video material, artwork, graphic material, databases, proprietary information and all copyrightable or otherwise legally protectable elements of the Site, including, without limitation, the selection, sequence and 'look and feel' and arrangement of items, and all trademarks, service marks and trade names (individually and/or collectively, "Material"), are the property of the Parent Companies, and their Affiliates, and any of their successors and assigns, and any of their respective licensors, Advertisers (as defined below), suppliers, and operational service providers and are legally protected, without limitation, under U.S. Federal and State, as well as applicable foreign laws, regulations and treaties. Unless the context clearly requires otherwise or we explicitly say so in writing, the term "Site" includes "Material" as well. The Site is to be used solely for your noncommercial, non-exclusive, non-assignable, non-transferable and limited personal use and for no other purposes. You must not alter, delete or conceal any copyright or other notices contained on the Site, including notices on any Material you download, transmit, display, print or reproduce from the Site. You shall not, nor will you allow any third party (whether or not for your benefit) to reproduce, modify, create derivative works from, display, perform, publish, distribute, disseminate, broadcast or circulate to any third party (including, without limitation, on or via a third party website), or otherwise use, any Material without the express prior written consent of RMC. Any unauthorized or prohibited use of any Material may subject you to civil liability, criminal prosecution, or both, under applicable federal, state and local laws. We require users to respect our copyrights, trademarks, and other intellectual property rights. We likewise respect the intellectual property of others. On notice, we will act expeditiously to remove content on the Site that infringes the copyright rights of others and will disable the access to the Site and its services of anyone who uses them to repeatedly to infringe the intellectual property rights of others.

<p />We take protection of copyrights, both our own and others, very seriously. We therefore employ multiple measures to prevent copyright infringement over this Site and to promptly end any infringement that might occur.

<p /><strong>4. ADVERTISING</strong>
<br />From time to time, you may communicate with, receive communications from, be re-directed to, interact with, or participate in or use the services or obtain goods and services of or from, third parties (collectively, the "Advertisers") such as our advertisers, sponsors, or promotional partners as a result of your use of the Site. All such communication, interaction and participation is strictly and solely between you and such Advertisers and we shall not be responsible or liable to you in any way in connection with these activities or transactions (including, without limitation, any representations, warranties, covenants, contracts or other terms or conditions that may exist between you and the Advertiser or any goods or services you may purchase or obtain from any Advertiser).

<p /><strong>5. RULES OF CONDUCT</strong>
<br />Your use of the Site is subject to all applicable local, state, national laws and regulations and, in some cases, international treaties. You are solely responsible for all activities, acts and omissions that occur in, from, through or under your user name or password. You shall not use, allow, or enable others to use the Site, or knowingly condone use of this Site by others, in any manner that is, attempts to, or is likely to:

<ul>
<li>be libelous, defamatory, indecent, vulgar or obscene, pornographic, sexually explicit or sexually suggestive, racially, culturally, or ethnically offensive, harmful, harassing, intimidating, threatening, hateful, objectionable, discriminatory, or abusive, or which may or may appear to impersonate anyone else;</li>
<li>affect us adversely or reflect negatively on us, the Site, our goodwill, name or reputation or cause duress, distress or discomfort to us or anyone else, or discourage any person, firm or enterprise from using all or any portion, features or functions of the Site, or from advertising, linking or becoming a supplier to us in connection with the Site;</li>
<li>send or result in the transmission of junk e-mail, chain letters, duplicative or unsolicited messages, or so-called "spamming" and "phishing";</li>
<li>be used for commercial or business purposes, including, without limitation, advertising, marketing or offering goods or services, whether or not for financial or any other form of compensation or through linking with any other website or web pages;</li>
<li>transmit, distribute or upload programs or material that contain malicious code, such as viruses, timebombs, cancelbots, worms, trojan horses, spyware, or other potentially harmful programs or other material or information;</li>
<li>forge any TCP/IP packet header or part of the header information in any email or newsgroup posting for any reason;</li>
<li>violate any laws, regulations (including, without limitation, laws regarding the transmission of technical data or software exported from the United States), judicial or governmental order or any treaties, or violate or infringe upon any intellectual property rights, rights of publicity or privacy, or any other rights of ours or of any other person, firm or enterprise; gain unauthorized access to the Site, other users' accounts, names, passwords, personally identifiable information or other computers, websites or pages, connected or linked to the Site or to use the Site in any manner which violates or is inconsistent with the terms and conditions of this Agreement;</li>
<li>modify, disrupt, impair, alter or interfere with the use, features, functions, operation or maintenance of the Site or the rights or use and enjoyment of the Site by any other person, firm or enterprise; or</li>
<li>collect, obtain, compile, gather, transmit, reproduce, delete, revise, view or display any material or information, whether personally identifiable or not, posted by or concerning any other person, firm or enterprise, in connection with their or your use of the Site, unless you have obtained the express, prior permission of such other person, firm or enterprise to do so.</li>
</ul>

<p /><strong>6. WIRELESS MARKETING SERVICES AND PROMOTIONAL OPPORTUNITIES</strong>
<br />The Site may provide its website users and viewers with the opportunity to register for special promotions, services, news, programming and information delivered via text messaging and other wireless Devices such as mobile phones. Users are required to provide their consent to receive such information from the Site, either by registering on this Site or via their wireless Device. Such services and promotional opportunities are provided by the Parent Companies or Affiliates for RMC. The information requested as part of the online registration process is a user's telephone number or a wireless email address, but only if specifically requested, and the carrier's name. Optional information may be requested for specific promotions, such as a user's preferences regarding goods or services, choices of music or artists, or other similar survey information. Depending on the promotion, we may also collect an Internet email address or other information and, depending on the information collected, the user may also be required to confirm his or her agreement to this Agreement, including, without limitation, its Privacy Policy . 

<p />Users that register for the Site's wireless marketing services acknowledge, understand and agree that they will be charged by the user's wireless carrier for all messages sent to the user from the Site. Standard messaging rates will apply, unless noted otherwise. Under no circumstances will the Site, RMC, the Parent Companies or any Affiliates be responsible for any wireless email or text messaging charges incurred by a user or by a person that has access to a user's wireless device, telephone number, or email address.

<p />A user understands, acknowledges and agrees that the Site may, at its sole discretion and without liability to any user, terminate its offer of any specific wireless marketing service or all wireless marketing services at any time without advance notice. The Site may provide notice of terminations or changes in services on this Site.


<p /><strong>7. POSTINGS</strong>
<br />Your comments, suggestions and information are important to us. Portions of this Site may provide you and other users an opportunity to participate in forum services, blogs, web communities and other message and communication facilities ("Communities") and may provide you with the opportunity, through such Communities or otherwise, to submit, post, display, transmit and/or exchange information, ideas, opinions, messages or other information ("Post" or "Postings"). You understand, acknowledge and agree that such Postings are the sole responsibility of the person from which such Postings originated. This means that you are solely and entirely responsible for the consequences of all Postings that you upload, post, email, transmit or otherwise make available via the Site. Postings do not reflect the views of the Site, RMC, the Parent Companies or the Affiliates. We reserve the right to monitor, edit or screen any Postings. If we determine, in our sole discretion and judgment, that any Posting does or may violate any of the terms of this Agreement, we reserve the right, at any time and without limiting any and all other rights we may have under this Agreement, at law or in equity, to: (a) refuse to allow you to Post; (b) remove and delete Postings; (c) revoke your right to use the Site; and/or (d) use any technological, legal, operational or other means available to us to enforce the provisions of this Agreement, including, without limitation, blocking specific IP addresses or deactivating your registration on the Site. 

<p />If a Posting originates from you or your account, you hereby agree that: (a) you specifically authorize the Site, RMC, the Parent Companies and their Affiliates to use such Posting in whole or in part, throughout the universe, in perpetuity in or on any and all media, now known or hereafter devised, and alone or together with or as part of other information, content and/or material of any kind or nature; (b) you represent and warrant that (i) the Posting is original to you and/or fully cleared for use as contemplated herein, (ii) the Posting does and will not, in any way, violate or breach any of the terms of this Agreement, (iii) the Posting does not contain libelous, tortious, or otherwise unlawful information, infringe or violate any copyright or other right, or contain any matter the publication or sale of which will violate any federal or state statute or regulation, (iv) the Posting is not obscene or in any other manner unlawful, (v) the Posting shall not be injurious to the health of any user, and (vi) we shall not be required to pay or incur any sums to any person or entity as a result of our use or exploitation of the Posting; and (c) if your Posting incorporates the name, logo, brand, service or trademark, voice, likeness or image of any person, firm or enterprise, you specifically represent and warrant that you (i) have the right to grant the Site, RMC, the Parent Companies and their Affiliates the right to use all such Postings as described above and (ii) the Posting was produced in compliance with all applicable laws and regulations.

<p />You understand, acknowledge and agree that we have the right to delete, re-format and/or change your Postings in any manner that we may determine (although you will not be responsible for any such changes made).

<p />The amount of storage space on the Site per user is limited. Some Postings may not be processed due to space constraints or outbound message limitations. You understand, acknowledge and agree that we assume no responsibility for deletion of Postings or any failure to store, receive or deliver Postings in a timely manner or any other matter relating to Postings.

<p />Posting is for noncommercial purposes only and you may not Post in any manner which does or is intended to promote or generate revenue for any business enterprise or commercial activity.


<p /><strong>8. CONTESTS, SWEEPSTAKES, AUCTIONS AND PROMOTIONS</strong>
<br />From time to time, RMC, the Parent Companies, the Affiliates or the Site's operational service providers, suppliers, and Advertisers, may conduct promotions on or through the Site, including, without limitation, auctions, contests and sweepstakes ("Promotions"). Each Promotion may have Additional Terms and/or Rules which will be posted or otherwise made available to you and, for purposes of each Promotion, will be deemed incorporated into and form a part of this Agreement.

<p /><strong>9. CERTAIN PRODUCTS AND SERVICES</strong>
<br />RSS Feeds and Podcasts The Site may provide RSS Feeds ("RSS Feeds") consisting of selected text, audio, video, and photographic content ("Content") from the Site that is provided over the Internet using an XML feed. Certain RSS Feeds may be podcasts ("Podcasts") which may include as part of the Content an associated audio, video and/or photographic file where the audio and/or video file may be downloaded and played from a user's Device or transferred to a portable listening device. Certain software and hardware is required for users to download and view and/or play Content through RSS Feeds. 

<p />Content is protected by U.S. Federal and State laws, and applicable foreign laws, regulation and treaties, and all rights in and to the Content are reserved to RMC or the content provider. Content is available for personal, noncommercial use only and you may download, copy and/or transfer to a Device or through a Device to another Device the RSS Feeds and associated Content for your personal, non-commercial use only. You shall not, nor will you allow any third party to reproduce, modify, create derivative works of, display, perform, publish, distribute, disseminate, broadcast or circulate to any third party, or otherwise use any Content except as expressly authorized in this Section 11.

<p />By your access to and use of RSS Feeds, you understand, acknowledge and agree that the Site, RMC, the Parent Companies and their Affiliates do not warrant that its RSS Feeds will operate on all user equipment. Please see the "Disclaimer and Limitations of Liability" section below for further details.


<p /><strong>10. HYPERLINKS TO THIRD PARTY SITES</strong>
<br />The appearance, availability, or your use of URLs or hyperlinks referenced or included anywhere on the Site or any other form of link or re-direction of your connection to, with or through the Site, does not constitute an endorsement by, nor does it incur any obligation, responsibility or liability on the part of the Site, RMC, the Parent Companies or any of their Affiliates, any of their successors and assigns, and any of their respective officers, directors, employees, agents, representatives, licensors, Advertisers, suppliers, and operational service providers. We do not verify, endorse, or have any responsibility for, any such third party sites, their business practices (including their privacy policies), or any goods or services associated with or obtained in connection with any such site, whether the Site's, RMC's, the Parent Companies' or any of their Affiliates' logo or sponsorship identification is on the third party site as part of a co-branding or promotional arrangement. If any third party site obtains or collects Personal Information from you, in no event shall we assume or have any responsibility or liability. Please read our Privacy Policy, which describes how RMC collects and uses your Personal Information and other information and certain of our relationships. 

<p /><strong>11. DEACTIVATION/TERMINATION OF YOUR REGISTRATION OR USE</strong>
<br />You may deactivate your account on the Site, at any time and for any reason, by emailing us at terms@ratemycampus.com. We may terminate your use of and registration on the Site, at any time and for any reason, with or without cause, without prior notice to you and without any liability or further obligation of any kind whatsoever to you or any other party. 

<p /><strong>12. DISCLAIMER AND LIMITATIONS OF LIABILITY</strong>
<br />THIS SITE, AND ALL MATERIALS, PRODUCTS AND POSTINGS ARE MADE AVAILABLE ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY REPRESENTATION OR WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, OR ANY GUARANTY OR ASSURANCE THE SITE WILL BE AVAILABLE FOR USE, OR THAT ALL PRODUCTS, FEATURES, FUNCTIONS OR OPERATIONS WILL BE AVAILABLE OR PERFORM AS DESCRIBED. Without limiting the foregoing, we are not responsible or liable for any malicious code, delays, inaccuracies, errors, or omissions arising out of your use of the Site. You understand, acknowledge and agree that you are assuming the entire risk as to the quality, accuracy, performance, timeliness, adequacy, completeness, correctness, authenticity, security and validity of any and all features and functions of the Site, including, without limitation, Postings and Materials associated with your use of the Site. 

<p />YOU UNDERSTAND AND AGREE THAT, TO THE FULLEST EXTENT PERMISSIBLE BY LAW, THIS SITE, RMC, THE PARENT COMPANIES, ANY OF THEIR AFFILIATES, OR THEIR RESPECTIVE SUCCESSORS AND ASSIGNS, OR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, LICENSORS, OPERATIONAL SERVICE PROVIDERS, ADVERTISERS, OR SUPPLIERS, SHALL NOT BE LIABLE FOR ANY LOSS OR DAMAGE, OF ANY KIND, DIRECT OR INDIRECT, IN CONNECTION WITH OR ARISING FROM USE OF THE SITE OR FROM THIS AGREEMENT, INCLUDING, BUT NOT LIMITED TO, COMPENSATORY, CONSEQUENTIAL, INCIDENTAL, INDIRECT, SPECIAL OR PUNITIVE DAMAGES. 

<p />Notwithstanding any claim that a sole or exclusive remedy which is provided in this Agreement may or does fail of its essential purpose, you specifically acknowledge and agree that your sole and exclusive remedy for any loss or damage shall be to have the Parent Companies, upon written notice from you to us, attempt to repair, correct or replace any deficient goods or services under this Agreement and, if repair, correction or replacement is not reasonably commercially practicable for the Parent Companies, to refund any monies actually paid by you for the Products involved and to terminate and discontinue your use of the Site. You further understand and acknowledge the capacity of the Site, in the aggregate and for each user, is limited. Consequently some messages and transmissions may not be processed in a timely fashion or at all, and some features or functions may be restricted or delayed or become completely inoperable. As a result, you acknowledge and agree that the Parent Companies assume no liability, responsibility or obligation to transmit, process, store, receive or deliver transactions or Postings or for any failure or delay associated with any Postings and you are hereby expressly advised not to rely upon the timeliness or performance of the Site for any transactions or Postings. Some jurisdictions do not allow for the exclusion of certain warranties or certain limitations on damages and remedies; accordingly some of the exclusions and limitations described in this Agreement may not apply to you. 

<p /><strong>13. INDEMNIFICATION</strong>
<br />You agree to indemnify, defend and hold the Site, RMC, the Parent Companies, and any of their Affiliates, or any of their successors and assigns, and any of their respective officers, directors, employees, agents, representatives, licensors, Advertisers, suppliers, and operational service providers harmless from and against any and all claims, actions, losses, expenses, damages and costs (including reasonable attorneys' fees), resulting from any breach or violation of this Agreement by you, or public posting of your Postings. 

<p />The Parent Companies reserves the right to assume, at its sole expense, the exclusive defense and control of any such claim or action and all negotiations for settlement or compromise, and you agree to fully cooperate with the Parent Companies in the defense of any such claim, action, settlement or compromise negotiations, as requested by the Parent Companies.

<p /><strong>14. ADS AND MALWARE</strong>
<br />We take great care and pride in creating this Site. We are always on the lookout for technical glitches that effect how the Site works. When we find them on our end, we will fix them. Unfortunately, your home computer may cause some glitches that effect how you see our Site -- and that is beyond our control. 

<p />If you experience any unusual behavior, content or ads on the Site, it may be the result of Malware on your computer. Malware --short for MALicious softWARE --is a term used to broadly classify a form of software which is installed in a computer system with malicious intentions, usually without the owner's knowledge or permission. Malware includes computer viruses, key loggers, malicious active content, rogue programs and dialers, among others. While we continuously work closely with our partners to ensure that everything on the Site is working properly, sometimes Malware programs on your personal computer may interfere with your experience on our Site and on other sites that you visit. 

<p />We suggest that you take some of the following actions which may help to clean your computer and which could prevent future installations of Malware. 

<ul>
<li>Update your computer via Windows Update or Software Update (on a Mac).</li>
<li>Install a SpyWare Removal Tool such as Spybot Search and Destroy or AdAware to clean your computer of Malware.</li>
<li>Install antivirus software, such as Norton anti-virus or McAfee Virus-shield.</li>
<li>Install Microsoft Defender (for Windows computers).</li>
</ul>

<p />Please note that we cannot be responsible for the effects of any third-party software including Malware on your computer system. Please make sure to carefully read the Help or Customer Support areas of any software download site. 

<p />If you do discover any Malware on your system, we also suggest you speak with a qualified computer technician. 

<p />If, after taking the above actions, you are still experiencing any problems, please feel free to contact us via the Contact Us page.

<p /><strong>15. PRIVACY</strong>
<br />We respect your privacy and the use and protection of your Personal Information. Please see our Privacy Policy , for important information and disclosures relating to the collection and use of your Personal Information in connection with your use of the Site. 

<p /><strong>16. LAW THAT APPLIES TO THIS AGREEMENT; MISCELLANEOUS TERMS</strong>
<br />This Agreement, together with any Additional Terms, Rules, our Privacy Policy, and any other regulations, procedures and policies which we refer to and which are hereby incorporated by reference, contains the entire understanding and agreement between you and the Site and supersedes any and all prior or inconsistent understandings relating to the Site and your use of the Site. This Agreement cannot be changed or terminated orally. If any provision of this Agreement is held to be illegal, invalid or unenforceable, this will not affect any other provisions and the Agreement will be deemed amended to the extent necessary to make it legal, valid and enforceable. Any provision which must survive in order to allow us to enforce its meaning shall survive the termination of this Agreement; however, no action arising out of this Agreement or your use of the Site, regardless of form or the basis of the claim, may be brought by you more than one (1) year after the cause of action has arisen (or if multiple causes, from the date the first such cause arose). 

<p />This Agreement and your use of the Site is governed by, construed and enforced in accordance with the internal substantive laws of the State of New York (notwithstanding the State's conflict of laws provisions) applicable to contracts made, executed and wholly performed in New York, and, for the purposes of any and all legal or equitable actions, you specifically agree and submit to the exclusive jurisdiction and venue of the State and Federal Courts situated in the State and County of New York and agree you will not object to such jurisdiction or venue on the grounds of lack of personal jurisdiction, forum non conveniens or otherwise. To the extent it may be applicable, you agree to opt out from and expressly exclude any applicability of the Uniform Computer Information Transactions Act. IN ANY ACTION OR PROCEEDING COMMENCED TO ENFORCE ANY RIGHT OR OBLIGATION OF THE PARTIES UNDER THIS AGREEMENT, YOUR USE OF THE SITE OR WITH RESPECT TO THE SUBJECT MATTER HEREOF, YOU HEREBY WAIVE ANY RIGHT YOU MAY NOW HAVE OR HEREAFTER POSSESS TO A TRIAL BY JURY. 

<p />This Terms of Use Agreement was last modified on 12/1/2012 and is effective immediately. 



<br /><br />

<p></p>